In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
sns.set(style='white', context='notebook', palette='Set2')

import matplotlib.pyplot as plt
%matplotlib inline

In [43]:
dataset = pd.read_csv("../dataset/online-data/dataset.csv")
dataset = dataset.drop(columns=["Unnamed: 0"])

In [44]:
dataset = dataset.replace( '\n', '', regex=True)
dataset = dataset.replace( '\r', ',', regex=True)
dataset = dataset.replace( 'Name: target, dtype: int64', '', regex=True)

In [45]:
dataset.replace({'Edinburgh': 'EDI', 'Liverpool': 'LVP', 'London': 'LON', 'Marseilles': 'MAR', 'Paris': 'PAR', 'Brest': 'BRE',
       'Venice': 'VEN', 'Rome': 'ROM', 'Naples': 'NAP', 'Munich': 'MUN', 'Berlin': 'BER', 'Kiel': 'KIE', 'Vienna': 'VIE',
       'Trieste': 'TRI', 'Budapest': 'BUD', 'Constantinople': 'CON', 'Ankara': 'ANK', 'Smyrna': 'SMY',
       'Moscow': 'MOS', 'St. Petersburg (South Coast)': '', 'Warsaw': 'WAR', 'Sevastopol': 'SEV',
       'Norwegian Sea': 'NWG', 'Yorkshire': 'YOR', 'North Sea': 'NTH', 'Spain': 'SPA', 'Picardy': 'PIC',
       'Mid-Atlantic Ocean': 'MAO', 'Tyrrhenian Sea': 'TYS', 'Silesia': 'SIL', 'Holland': 'HOL',
       'Albania': 'ALB', 'Serbia': 'SER', 'Bulgaria': 'BUL', 'St. Petersburg': 'STP',
       'Gulf of Bothnia': 'GOB', 'Ukraine': 'UKR', 'Norway': 'NWY', 'Belgium': 'BEL', 'Portugal': 'POR',
       'Piedmont': 'PIA', 'Tunis': 'TUN', 'Galicia': 'GAL', 'Greece': 'GRE', 'Black Sea': 'BLA', 'Finland': 'FIN',
       'Sweden': 'SWE', 'Rumania': 'RUM', 'Helgoland Bight': 'HEL', 'Burgundy': 'BUR',
       'English Channel': 'ENC', 'Tyrolia': 'TYR', 'Ionian Sea': 'IOS', 'Denmark': 'DEN', 'Wales': 'WAL',
       'Irish Sea': 'IRS', 'Armenia': 'ARM', 'St. Petersburg (North Coast)': 'STPNC',
       'North Atlantic Ocean': 'NAO', 'Ruhr': 'RUH', 'Aegean Sea': 'AES', 'Apulia': 'APU',
       'Skagerrack': 'SKA', 'nan': 'NAN', 'Gascony': 'GAS', 'Prussia': 'PRU', 'Barents Sea': 'BAR', 'Bohemia': 'BOH',
       'Adriatic Sea': 'ADS', 'Western Mediterranean': 'WMS', 'Tuscany': 'TUS', 'Baltic Sea': 'BAL',
       'Gulf of Lyons': 'GOL', 'Eastern Mediterranean': 'EMS', 'Spain (North Coast)': 'SPNC',
       'Syria': 'SYR', 'Livonia': 'LIV', 'Clyde': 'CLY', 'Spain (South Coast)': 'SPSC', 'North Africa': 'NAF',
       'Bulgaria (South Coast)': 'BUSC', 'Bulgaria (East Coast)':'BUEC'}, regex=True)

,in,out1,out2
0,1901SpringE,"NTH 3448,NWG 2271,YOR 1...","NTH 23295,NWG 14481,YOR ..."
1,1901SpringF,"MAO 2849,SPA 2307,BUR ...","MAO 17869,SPA 16283,BUR ..."
2,1901SpringI,"IOS 2084,VEN 803,APU ...","IOS 18967,APU 7004,VEN ..."
3,1901SpringG,"KIE 3599,DEN 2704,RUH...","KIE 19917,DEN 14190,R..."
4,1901SpringA,"SER 3031,ALB 2626,BUD ...","SER 18986,ALB 14462,BUD ..."
5,1901SpringT,"BUL 5311,CON 3990,BLA 2115...","BUL 24773,CON 18643,BLA 7..."
6,1901SpringR,"GOB 4690,UKR 4074,GAL ...","GOB 22190,UKR ..."
7,1901FallE,"NWY 3050,fleet LON ...","NWY 18315,YOR 1..."
8,1901FallF,"POR 3008,army PAR ...","POR 17374,army PAR ..."
9,1901FallI,"TUN 1776,fleet NAP ...","TUN 16970,fleet NAP ..."
10,1901FallG,"army MUN 2584,HOL 2515,fleet...","HOL 12442,army MUN 118..."
11,1901FallA,"army BUD 2553,GRE 2390,army VIE...","army BUD 12598,GRE 10708,army V..."
12,1901FallT,"fleet SMY 3120,BUL ...","fleet SMY 13389,BUL ..."
13,1901FallR,"SWE 4082,RUM ...","SWE 15497,RUM ..."
14,1902SpringE,"NTH 1608,ENC ...","NTH 8490,NWY ..."
15,1902SpringF,"MAO 2248,BUR 1879,PIC ...","MAO 11981,BUR 9364,PIC ..."
16,1902SpringI,"IOS 1284,TYS 716,VE...","IOS 9342,TYS 7294,VE..."
17,1902SpringG,"KIE 1454,RUH ...","RUH 7894,KIE ..."
18,1902SpringA,"SER 1703,GAL ...","SER 7006,BUD ..."
19,1902SpringT,"BUL 3236,AES 2...","BUL 11296,AES ..."
20,1902SpringR,"RUM 2545,GAL ...","RUM 8731,GAL ..."
21,1902FallE,"NWY 1258,fleet LON ...","NWY 6572,fleet LON ..."
22,1902FallF,"BUR 1354,BEL ...","BUR 7244,BEL ..."
23,1902FallI,"fleet NAP 1032,TUN ...","TUN 7163,fleet NAP ..."
24,1902FallG,"army BER 1362,BEL ...","BEL 5437,MUN ..."
25,1902FallA,"army VIE 1510,RUM ...","TRI 5168,SER ..."
26,1902FallT,"BUL 2492,fleet SMY ...","BUL 9141,fleet SMY ..."
27,1902FallR,"RUM 2703,army WA...","RUM 8081,army WA..."
28,1903SpringE,"NTH 1405,NWY ...","NTH 6910,NWY ..."
29,1903SpringF,"BUR 1639,BEL ...","BUR 7988,MAO ..."
...,...,...,...
264,1919FallT,"IOS 70,TYS 68,WAR ...","IOS 101,TYS ..."
265,1919FallR,"MUN 17,NWY ...","MUN 28,MOS ..."
266,1920SpringE,"MUN 33,LON ...","TUN 43,MAO ..."
267,1920SpringF,"MAO 13,IOS 1...","MAO 28,MAR 2..."
268,1920SpringI,"VEN 6,TRI 4...","TYS 13,VEN 13,WMS ..."
269,1920SpringG,"MOS 33,TYR ...","MUN 65,BER ..."
270,1920SpringA,"TYR 10,PIA 10...","TRI 56,TYS 27,SER ..."
271,1920SpringT,"TYS 36,TUS 35,VIE ...","TUS 40,TYS ..."
272,1920SpringR,"MUN 9,NWY ...","MUN 19,NWY ..."
273,1920FallE,"MAO 58,ENC 40,MUN...","MAO 73,ENC 50,MUN..."
274,1920FallF,"MUN 11,KIE ...","MAR 27,MUN ..."
275,1920FallI,"MUN 7,PIA 6,...","PIA 13,WMS 13,MUN ..."
276,1920FallG,"TYR 35,BUD 33...","MUN 67,TYR ..."
277,1920FallA,"MUN 9,IOS 8,WA...","TRI 41,SER ..."
278,1920FallT,"GAL 24,ROM ...","IOS 31,GAL 26..."
279,1920FallR,"MUN 12,BER ...","MUN 18,BER ..."
280,1921SpringE,"WMS 53,MAR 50,M...","WMS 58,MAO 52,MAR ..."
281,1921SpringF,"MAO 9,RUH ...","MAO 24,MAR 1..."
282,1921SpringI,"TYS 6,MUN 5,RUM ...","TYS 9,PIA 9,TYR ..."
283,1921SpringG,"TYR 37,BUD 32...","MUN 65,TYR ..."
284,1921SpringA,"WAR 9,MUN ...","TRI 55,VEN ..."
285,1921SpringT,"WAR 24,PIA ...","WAR 29,PIA ..."
286,1921SpringR,"BER 8,MUN ...","MUN 13,NWY ..."
287,1921FallE,"TUN 39,PIA ...","GOL 59,TUN ..."
288,1921FallF,"army PAR 8,MUN ...","MUN 19,MAO ..."
289,1921FallI,"WMS 6,MAR 5,MAO 5,VEN ...","WMS 10,GOL 8,MAR ..."
290,1921FallG,"BUD 34,TYR 20...","MUN 64,BUD 3..."
291,1921FallA,"TYS 7,TYR 7,GAL ...","TRI 39,TUS 3..."
292,1921FallT,"TYS 19,PRU 17,WAR ...","TYS 27,IOS 25,PRU ..."
293,1921FallR,"MUN 8,GAL ...","MUN 16,BER ..."

In [46]:
dataset.to_csv("new.csv")